spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scarlett
    password: Yangjing95

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    serialization:
      indent_output: true

  thymeleaf:
    cache: false

  batch:
    job:
      enabled: false


logging:
  level:
    org:
      springframwork:
        security: info
